name: flutter_final_project_provincevu
description: "A new Flutter project."

# This prevents the package from being accidentally published to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Application version and build number
version: 1.0.0+1

# Specify the SDK version for Dart/Flutter
environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  localstore: ^1.4.0

  # Adds Cupertino-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
